[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "libpng", "libjpeg", "freetype", "zlib"]

[phases.install]
cmds = ["composer install --no-dev --ignore-platform-req=ext-gd --optimize-autoloader --no-interaction"]

[phases.build]
cmds = ["php artisan config:clear || true"]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
